[workspace]
members = [
    ".",                        # dodaj root kao member
    "crates/engine",
    "crates/interval", "crates/query",
    "crates/temporal_graph",
    "crates/tql_parser",
    "crates/visualization"
]
resolver = "2"

[workspace.dependencies]
tokio     = { version = "1", features = ["full"] }
clap      = { version = "4.6.1", features = ["derive"] }
tracing   = "0.1.44"
anyhow    = "1.0.104"
tracing-subscriber = "0.3.23"

[package]
name = "graphstream"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio     = { workspace = true }
clap      = { workspace = true }
anyhow    = { workspace = true }
tracing-subscriber = "0.3.23"
log = "0.4.33"
tracing = "0.1.44"
engine          = { path = "crates/engine" }
temporal_graph  = { path = "crates/temporal_graph" }
visualization  = {path = "crates/visualization"}
query           = {path ="crates/query"}